#!/usr/bin/env bash
set -Eeuo pipefail

#cd "$(dirname "$(readlink -f "$BASH_SOURCE")")"

echo "Version:"
echo $@
versions=( "$@" )
echo $versions
echo "=="
if [ ${#versions[@]} -eq 0 ]; then
	versions=( */ )
  echo $versions
fi
versions=( "${versions[@]%/}" )

generated_warning() {
	cat <<-EOH
		#
		# NOTE: THIS DOCKERFILE IS GENERATED VIA "update.sh"
		#
		# PLEASE DO NOT EDIT IT DIRECTLY.
		#

	EOH
}

dockerfiles=()

travisEnv=
for version in "${versions[@]}"; do

  echo "Running version $version"

	dockerfiles=()

	for suite in stretch; do
		[ -d "$version/$suite" ] || continue

		baseDockerfile=Dockerfile-debian.template

    for db in psql mssql oci; do
      [ -d "$version/$suite/$db" ] || continue

      for variant in base ci; do
        [ -d "$version/$suite/$db/$variant" ] || continue

        dockerfile="$version/$suite/$db/$variant/Dockerfile"

        echo "Generating $dockerfile from $baseDockerfile"
        { generated_warning; cat "$baseDockerfile"; } > "$dockerfile"

        echo " Applying PHP Version to $dockerfile from $version-Dockerfile-block-*"
        gawk -i inplace -v version="$version" '
          $1 == "##</autogenerated-phpversion>##" { ia = 0 }
          !ia { print }
          $1 == "##<autogenerated-phpversion>##" { ia = 1; ab++; ac = 0; if (system("test -f " version "-Dockerfile-block-" ab) != 0) { ia = 0 } }
          ia { ac++ }
          ia && ac == 1 { system("cat " version "-Dockerfile-block-" ab) }
        ' "$dockerfile"

        echo " Applying DB to $dockerfile from $db-Dockerfile-block-*"
        gawk -i inplace -v db="$db" '
          $1 == "##</autogenerated-db>##" { ia = 0 }
          !ia { print }
          $1 == "##<autogenerated-db>##" { ia = 1; ab++; ac = 0; if (system("test -f " db "-Dockerfile-block-" ab) != 0) { ia = 0 } }
          ia { ac++ }
          ia && ac == 1 { system("cat " db "-Dockerfile-block-" ab) }
        ' "$dockerfile"

        echo " Applying Variant to $dockerfile from $variant-Dockerfile-block-*"
        gawk -i inplace -v variant="$variant" '
          $1 == "##</autogenerated-variant>##" { ia = 0 }
          !ia { print }
          $1 == "##<autogenerated-variant>##" { ia = 1; ab++; ac = 0; if (system("test -f " variant "-Dockerfile-block-" ab) != 0) { ia = 0 } }
          ia { ac++ }
          ia && ac == 1 { system("cat " variant "-Dockerfile-block-" ab) }
        ' "$dockerfile"

        cp -a \
          moodle-php-entrypoint \
          nvm-wrapper \
          "$version/$suite/$db/$variant/"

        # Remove any _extra_ blank lines created by the deletions above.
        awk '
          NF > 0 { blank = 0 }
          NF == 0 { ++blank }
          blank < 2 { print }
        ' "$dockerfile" > "$dockerfile.new"
        mv "$dockerfile.new" "$dockerfile"

        sed -ri \
          -e 's!%%DEBIAN_TAG%%!'"$suite"'!' \
          -e 's!%%DEBIAN_SUITE%%!'"$suite"'!' \
          -e 's!%%VERSION%%!'"$version"'!' \
          "$dockerfile"
        dockerfiles+=( "$dockerfile" )

      done

    done

	done

  echo ${dockerfiles}
done
